parameters:
#    sm_front.example.class: SM\Bundle\FrontBundle\Example

services:
#    sm_front.example:
#        class: %sm_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
